#!/usr/bin/env bash

if [ "$1" == "gen-doc" ]; then
    docker run --rm \
        -u $(id -u):$(id -g) \
        -v $PWD:/app \
        -w /app \
        composer:latest php doctum update config.php

else
    docker run --rm \
        -u $(id -u):$(id -g) \
        -v $PWD:/app \
        -w /app \
        composer:latest "$@"
fi
